name: fastapi CI

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: python main.py
    
    
